//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the RESX Manager tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FleetManager.Exception.ExceptionBase {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        public ResourceErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    var temp = new global::System.Resources.ResourceManager("FleetManager.Exception.ExceptionBase.ResourceErrorMessages", typeof(ResourceErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

		/// <summary>
		/// 
		/// </summary>
		public static string ADDRESS_NOT_FOUND => ResourceManager.GetString("ADDRESS_NOT_FOUND", resourceCulture);

		/// <summary>
		/// 
		/// </summary>
		public static string BRAND_REQUIRED => ResourceManager.GetString("BRAND_REQUIRED", resourceCulture);

		/// <summary>
		/// 
		/// </summary>
		public static string CATEGORY_ID_INVALID => ResourceManager.GetString("CATEGORY_ID_INVALID", resourceCulture);

		/// <summary>
		/// 
		/// </summary>
		public static string CATEGORY_NOT_FOUND => ResourceManager.GetString("CATEGORY_NOT_FOUND", resourceCulture);

		/// <summary>
		/// 
		/// </summary>
		public static string CHASSIS_NUMBER_INVALID => ResourceManager.GetString("CHASSIS_NUMBER_INVALID", resourceCulture);

		/// <summary>
		/// 
		/// </summary>
		public static string CHASSIS_NUMBER_REQUIRED => ResourceManager.GetString("CHASSIS_NUMBER_REQUIRED", resourceCulture);

		/// <summary>
		/// 
		/// </summary>
		public static string CITY_REQUIRED => ResourceManager.GetString("CITY_REQUIRED", resourceCulture);

		/// <summary>
		/// 
		/// </summary>
		public static string COLOR_REQUIRED => ResourceManager.GetString("COLOR_REQUIRED", resourceCulture);

		/// <summary>
		/// 
		/// </summary>
		public static string CREATE_AT_INVALID => ResourceManager.GetString("CREATE_AT_INVALID", resourceCulture);

		/// <summary>
		/// 
		/// </summary>
		public static string CURRENT_MILEAGE_EMPTY => ResourceManager.GetString("CURRENT_MILEAGE_EMPTY", resourceCulture);

		/// <summary>
		/// 
		/// </summary>
		public static string EMAIL_ALREADY_REGISTERED => ResourceManager.GetString("EMAIL_ALREADY_REGISTERED", resourceCulture);

		/// <summary>
		/// 
		/// </summary>
		public static string EMAIL_INVALID => ResourceManager.GetString("EMAIL_INVALID", resourceCulture);

		/// <summary>
		/// 
		/// </summary>
		public static string EMAIL_OR_PASSWORD_INVALID => ResourceManager.GetString("EMAIL_OR_PASSWORD_INVALID", resourceCulture);

		/// <summary>
		/// 
		/// </summary>
		public static string EMAIL_REQUIRED => ResourceManager.GetString("EMAIL_REQUIRED", resourceCulture);

		/// <summary>
		/// 
		/// </summary>
		public static string FUEL_TYPE_INVALID => ResourceManager.GetString("FUEL_TYPE_INVALID", resourceCulture);

		/// <summary>
		/// 
		/// </summary>
		public static string INVALID_LENGTH => ResourceManager.GetString("INVALID_LENGTH", resourceCulture);

		/// <summary>
		/// 
		/// </summary>
		public static string INVALID_PASSWORD => ResourceManager.GetString("INVALID_PASSWORD", resourceCulture);

		/// <summary>
		/// 
		/// </summary>
		public static string LICENSE_PLATE_INVALID_FORMAT => ResourceManager.GetString("LICENSE_PLATE_INVALID_FORMAT", resourceCulture);

		/// <summary>
		/// 
		/// </summary>
		public static string LICENSE_PLATE_MUST_BE_7_CHARACTERS_LONG => ResourceManager.GetString("LICENSE_PLATE_MUST_BE_7_CHARACTERS_LONG", resourceCulture);

		/// <summary>
		/// 
		/// </summary>
		public static string LICENSE_PLATE_REQUIRED => ResourceManager.GetString("LICENSE_PLATE_REQUIRED", resourceCulture);

		/// <summary>
		/// 
		/// </summary>
		public static string MANUFACTURE_MUST_BE_GREATER_THAN_OR_EQUAL_TO_2010 => ResourceManager.GetString("MANUFACTURE_MUST_BE_GREATER_THAN_OR_EQUAL_TO_2010", resourceCulture);

		/// <summary>
		/// 
		/// </summary>
		public static string MODEL_REQUIRED => ResourceManager.GetString("MODEL_REQUIRED", resourceCulture);

		/// <summary>
		/// 
		/// </summary>
		public static string MUST_BE_GREATER_THAN_ZERO => ResourceManager.GetString("MUST_BE_GREATER_THAN_ZERO", resourceCulture);

		/// <summary>
		/// 
		/// </summary>
		public static string NAME_REQUIRED => ResourceManager.GetString("NAME_REQUIRED", resourceCulture);

		/// <summary>
		/// 
		/// </summary>
		public static string NOT_FOUND => ResourceManager.GetString("NOT_FOUND", resourceCulture);

		/// <summary>
		/// 
		/// </summary>
		public static string NUMBER_REQUIRED => ResourceManager.GetString("NUMBER_REQUIRED", resourceCulture);

		/// <summary>
		/// 
		/// </summary>
		public static string PASSWORD_MUST_CONTAIN_AN_LOWRECASE_LETTER => ResourceManager.GetString("PASSWORD_MUST_CONTAIN_AN_LOWRECASE_LETTER", resourceCulture);

		/// <summary>
		/// 
		/// </summary>
		public static string PASSWORD_MUST_CONTAIN_AN_UPPERCASE_LETTER => ResourceManager.GetString("PASSWORD_MUST_CONTAIN_AN_UPPERCASE_LETTER", resourceCulture);

		/// <summary>
		/// 
		/// </summary>
		public static string PASSWORD_MUST_CONTAIN_NUMBER => ResourceManager.GetString("PASSWORD_MUST_CONTAIN_NUMBER", resourceCulture);

		/// <summary>
		/// 
		/// </summary>
		public static string RENAVAM_REQUIRED => ResourceManager.GetString("RENAVAM_REQUIRED", resourceCulture);

		/// <summary>
		/// 
		/// </summary>
		public static string STATE_REQUIRED => ResourceManager.GetString("STATE_REQUIRED", resourceCulture);

		/// <summary>
		/// 
		/// </summary>
		public static string STREET_REQUIRED => ResourceManager.GetString("STREET_REQUIRED", resourceCulture);

		/// <summary>
		/// 
		/// </summary>
		public static string THE_MILEAGE_MUST_BE_HIGHER_THAN_THE_CURRENT => ResourceManager.GetString("THE_MILEAGE_MUST_BE_HIGHER_THAN_THE_CURRENT", resourceCulture);

		/// <summary>
		/// 
		/// </summary>
		public static string TRANSMISSION_TYPE_INVALID => ResourceManager.GetString("TRANSMISSION_TYPE_INVALID", resourceCulture);

		/// <summary>
		/// 
		/// </summary>
		public static string UNKNOW_ERROR => ResourceManager.GetString("UNKNOW_ERROR", resourceCulture);

		/// <summary>
		/// 
		/// </summary>
		public static string VEHICLE_NOT_FOUND => ResourceManager.GetString("VEHICLE_NOT_FOUND", resourceCulture);

		/// <summary>
		/// 
		/// </summary>
		public static string ZIPCODE_INVALID => ResourceManager.GetString("ZIPCODE_INVALID", resourceCulture);

		/// <summary>
		/// 
		/// </summary>
		public static string ZIPCODE_REQUIRED => ResourceManager.GetString("ZIPCODE_REQUIRED", resourceCulture);

	}
}