//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FleetManager.Exception.ExceptionBase {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceExtensionsMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceExtensionsMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FleetManager.Exception.ExceptionBase.ResourceExtensionsMessages", typeof(ResourceExtensionsMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string ACTIVE {
            get {
                return ResourceManager.GetString("ACTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        public static string AVAILABLE {
            get {
                return ResourceManager.GetString("AVAILABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocked for maintenance.
        /// </summary>
        public static string BLOCKED_FOR_MAINTENANCE {
            get {
                return ResourceManager.GetString("BLOCKED_FOR_MAINTENANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        public static string CANCELLED {
            get {
                return ResourceManager.GetString("CANCELLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed.
        /// </summary>
        public static string CLOSED {
            get {
                return ResourceManager.GetString("CLOSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily.
        /// </summary>
        public static string DAILY {
            get {
                return ResourceManager.GetString("DAILY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivate.
        /// </summary>
        public static string DEACTIVATE {
            get {
                return ResourceManager.GetString("DEACTIVATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delinquent.
        /// </summary>
        public static string DELINQUENT {
            get {
                return ResourceManager.GetString("DELINQUENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excess mileage fee ({0} km over contract).
        /// </summary>
        public static string EXCESS_MILEAGE_CHARGE_DESCRIPTION {
            get {
                return ResourceManager.GetString("EXCESS_MILEAGE_CHARGE_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished.
        /// </summary>
        public static string FINISHED {
            get {
                return ResourceManager.GetString("FINISHED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        public static string HIGH {
            get {
                return ResourceManager.GetString("HIGH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        public static string INACTIVE {
            get {
                return ResourceManager.GetString("INACTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Late return fee ({0} day(s) late).
        /// </summary>
        public static string LATE_FEE_CHARGE_DESCRIPTION {
            get {
                return ResourceManager.GetString("LATE_FEE_CHARGE_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        public static string LOW {
            get {
                return ResourceManager.GetString("LOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance.
        /// </summary>
        public static string MAINTENANCE {
            get {
                return ResourceManager.GetString("MAINTENANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly.
        /// </summary>
        public static string MONTHLY {
            get {
                return ResourceManager.GetString("MONTHLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overdue.
        /// </summary>
        public static string OVERDUE {
            get {
                return ResourceManager.GetString("OVERDUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid.
        /// </summary>
        public static string PAID {
            get {
                return ResourceManager.GetString("PAID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        public static string PENDING {
            get {
                return ResourceManager.GetString("PENDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renewed.
        /// </summary>
        public static string RENEWED {
            get {
                return ResourceManager.GetString("RENEWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rented.
        /// </summary>
        public static string RENTED {
            get {
                return ResourceManager.GetString("RENTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reported.
        /// </summary>
        public static string REPORTED {
            get {
                return ResourceManager.GetString("REPORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserved.
        /// </summary>
        public static string RESERVED {
            get {
                return ResourceManager.GetString("RESERVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolved.
        /// </summary>
        public static string RESOLVED {
            get {
                return ResourceManager.GetString("RESOLVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduled.
        /// </summary>
        public static string SCHEDULED {
            get {
                return ResourceManager.GetString("SCHEDULED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unavailable.
        /// </summary>
        public static string UNAVAILABLE {
            get {
                return ResourceManager.GetString("UNAVAILABLE", resourceCulture);
            }
        }
    }
}
