//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FleetManager.Exception.ExceptionBase {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FleetManager.Exception.ExceptionBase.ResourceErrorMessages", typeof(ResourceErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand required.
        /// </summary>
        public static string BRAND_REQUIRED {
            get {
                return ResourceManager.GetString("BRAND_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category id invalid.
        /// </summary>
        public static string CATEGORY_ID_INVALID {
            get {
                return ResourceManager.GetString("CATEGORY_ID_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category not found.
        /// </summary>
        public static string CATEGORY_NOT_FOUND {
            get {
                return ResourceManager.GetString("CATEGORY_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color required.
        /// </summary>
        public static string COLOR_REQUIRED {
            get {
                return ResourceManager.GetString("COLOR_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create at invalid.
        /// </summary>
        public static string CREATE_AT_INVALID {
            get {
                return ResourceManager.GetString("CREATE_AT_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current milieage empty.
        /// </summary>
        public static string CURRENT_MILEAGE_EMPTY {
            get {
                return ResourceManager.GetString("CURRENT_MILEAGE_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fuel type invalid.
        /// </summary>
        public static string FUEL_TYPE_INVALID {
            get {
                return ResourceManager.GetString("FUEL_TYPE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid length.
        /// </summary>
        public static string INVALID_LENGTH {
            get {
                return ResourceManager.GetString("INVALID_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License plate invalid format.
        /// </summary>
        public static string LICENSE_PLATE_INVALID_FORMAT {
            get {
                return ResourceManager.GetString("LICENSE_PLATE_INVALID_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License plate must be 7 characters long.
        /// </summary>
        public static string LICENSE_PLATE_MUST_BE_7_CHARACTERS_LONG {
            get {
                return ResourceManager.GetString("LICENSE_PLATE_MUST_BE_7_CHARACTERS_LONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License plate required.
        /// </summary>
        public static string LICENSE_PLATE_REQUIRED {
            get {
                return ResourceManager.GetString("LICENSE_PLATE_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacture must be greater than or equal to 2010.
        /// </summary>
        public static string MANUFACTURE_MUST_BE_GREATER_THAN_OR_EQUAL_TO_2010 {
            get {
                return ResourceManager.GetString("MANUFACTURE_MUST_BE_GREATER_THAN_OR_EQUAL_TO_2010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model required.
        /// </summary>
        public static string MODEL_REQUIRED {
            get {
                return ResourceManager.GetString("MODEL_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must Be Greater than zero.
        /// </summary>
        public static string MUST_BE_GREATER_THAN_ZERO {
            get {
                return ResourceManager.GetString("MUST_BE_GREATER_THAN_ZERO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name required.
        /// </summary>
        public static string NAME_REQUIRED {
            get {
                return ResourceManager.GetString("NAME_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found.
        /// </summary>
        public static string NOT_FOUND {
            get {
                return ResourceManager.GetString("NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renavam required.
        /// </summary>
        public static string RENAVAM_REQUIRED {
            get {
                return ResourceManager.GetString("RENAVAM_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transmission type invalid.
        /// </summary>
        public static string TRANSMISSION_TYPE_INVALID {
            get {
                return ResourceManager.GetString("TRANSMISSION_TYPE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknow error.
        /// </summary>
        public static string UNKNOW_ERROR {
            get {
                return ResourceManager.GetString("UNKNOW_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle not found.
        /// </summary>
        public static string VEHICLE_NOT_FOUND {
            get {
                return ResourceManager.GetString("VEHICLE_NOT_FOUND", resourceCulture);
            }
        }
    }
}
