<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
	  <Compile Remove="UseCase\ToTenant\Active\**" />
	  <Compile Remove="UseCase\ToTenant\Desactive\**" />
	  <EmbeddedResource Remove="UseCase\ToTenant\Active\**" />
	  <EmbeddedResource Remove="UseCase\ToTenant\Desactive\**" />
	  <None Remove="UseCase\ToTenant\Active\**" />
	  <None Remove="UseCase\ToTenant\Desactive\**" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\FleetManager.Communication\FleetManager.Communication.csproj" />
		<ProjectReference Include="..\FleetManager.Domain\FleetManager.Domain.csproj" />
		<ProjectReference Include="..\FleetManager.Exception\FleetManager.Exception.csproj" />
		<ProjectReference Include="..\FleetManager.Infrastructure\FleetManager.Infrastructure.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="FluentValidation" Version="12.1.1" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="UseCase\ToMaintenance\Close\" />
	  <Folder Include="UseCase\ToMaintenance\Delete\" />
	  <Folder Include="UseCase\ToMaintenance\GetById\" />
	  <Folder Include="UseCase\ToVehicle\Active\" />
	  <Folder Include="UseCase\ToVehicle\Desactive\" />
	</ItemGroup>

</Project>
