//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FleetManager.Domain.DomainExceptionBase {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FleetManager.Domain.DomainExceptionBase.ResourceMessages", typeof(ResourceMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin already exists.
        /// </summary>
        public static string ADMIN_ALREADY_EXISTS {
            get {
                return ResourceManager.GetString("ADMIN_ALREADY_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot completed rental..
        /// </summary>
        public static string CANNOT_CANCEL_COMPLETED_RENTAL {
            get {
                return ResourceManager.GetString("CANNOT_CANCEL_COMPLETED_RENTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot complete concelled rental..
        /// </summary>
        public static string CANNOT_COMPLETE_CANCELLED_RENTAL {
            get {
                return ResourceManager.GetString("CANNOT_COMPLETE_CANCELLED_RENTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Reschedule non active rental.
        /// </summary>
        public static string CANNOT_RESCHEDULE_NON_ACTIVE_RENTAL {
            get {
                return ResourceManager.GetString("CANNOT_RESCHEDULE_NON_ACTIVE_RENTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date must be greater than start date..
        /// </summary>
        public static string END_DATE_MUST_BE_GREATER_THAN_START_DATE {
            get {
                return ResourceManager.GetString("END_DATE_MUST_BE_GREATER_THAN_START_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Included km cannot be negative..
        /// </summary>
        public static string INCLUDED_KM_CANNOT_BE_NEGATIVE {
            get {
                return ResourceManager.GetString("INCLUDED_KM_CANNOT_BE_NEGATIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price cannot be negative..
        /// </summary>
        public static string PRICE_CANNOT_BE_NEGATIVE {
            get {
                return ResourceManager.GetString("PRICE_CANNOT_BE_NEGATIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rental cannot be markd overdue..
        /// </summary>
        public static string RENTAL_CANNOT_BE_MARKED_OVERDUE {
            get {
                return ResourceManager.GetString("RENTAL_CANNOT_BE_MARKED_OVERDUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rental Plan cannot be null..
        /// </summary>
        public static string RENTAL_PLAN_CANNOT_BE_NULL {
            get {
                return ResourceManager.GetString("RENTAL_PLAN_CANNOT_BE_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rental plan is not active..
        /// </summary>
        public static string RENTAL_PLAN_IS_NOT_ACTIVE {
            get {
                return ResourceManager.GetString("RENTAL_PLAN_IS_NOT_ACTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The miliage must be higher than the current..
        /// </summary>
        public static string THE_MILEAGE_MUST_BE_HIGHER_THAN_THE_CURRENT {
            get {
                return ResourceManager.GetString("THE_MILEAGE_MUST_BE_HIGHER_THAN_THE_CURRENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User already admin..
        /// </summary>
        public static string USER_ALREADY_ADMIN {
            get {
                return ResourceManager.GetString("USER_ALREADY_ADMIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found.
        /// </summary>
        public static string USER_NOT_FOUND {
            get {
                return ResourceManager.GetString("USER_NOT_FOUND", resourceCulture);
            }
        }
    }
}
